### ISSUE TITLE
committee meeting attendees support

### ISSUE THREAD

**Issue by RavivBarzilay** [hasadna/knesset-data-pipelines#11]
* support in the people attending committees
* should have a dashboard which shows all the data (like the [committees dashboard](https://next.oknesset.org/metabase/public/dashboard/57604bd2-73f3-4fbc-943f-53bf45287641))

**Comment by OriHoch** [comment]
@RavivBarzilay current status - 
* merged the changes, but still waiting to see data, the meeting processor is failing, not sure if related to your work or not.. need to investigate
* once we see data - need to add this table to the [committees metabase dashboard](http://next.oknesset.org/metabase/public/dashboard/57604bd2-73f3-4fbc-943f-53bf45287641)

**Comment by OriHoch** [comment]
I fixed some bugs, see:
https://github.com/hasadna/knesset-data-pipelines/commit/852bb812fbcfcba95f6b581b59e4281bc15eb73f#diff-4c30733200b7b0d48c6559a24b4c7f97
https://github.com/hasadna/knesset-data-python/commit/649e109002a2ef4e6dad484dbaaa3454e673abbe

merged and deployed, meetings pipeline is running - https://next.oknesset.org/pipelines/

**Comment by OriHoch** [comment]
:goberserk: it failed.. bug with minio this time..  I'm checking

**Comment by OriHoch** [comment]
fixed.. waiting for deployment and pipelines to run

**Comment by OriHoch** [comment]
it ran! I added the data to the dashboard - http://next.oknesset.org/metabase/public/dashboard/57604bd2-73f3-4fbc-943f-53bf45287641
