### ISSUE TITLE
add votes data

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data-pipelines#12]
should have votes pipeline - which gets data from the knesset-data-python dataservice classes

I think there is also some votes related code in knesset-data-python html scrapers

**Comment by OriHoch** [comment]
@gilwo - you are working on it?

**Comment by gilwo** [comment]
yes i am on it

**Comment by OriHoch** [comment]
the html scraper is [here](https://github.com/hasadna/knesset-data-python/blob/master/knesset_data/html_scrapers/votes.py), currently it's the only option to get the breakdown of how each member voted on a specific vote

in Open Knesset we had some code that simply iterated over the vote numbers, and skipped loading from dataservice altogether

the vote numbers are sequential, so if we have a pipeline that loads them to DB, this pipeline can just look at last vote number in DB and just iterate e.g. 1000 numbers from that
