### ISSUE TITLE
Seeking Vote By Bill

### ISSUE THREAD

**Issue by galvinograd** [hasadna/knesset-data-pipelines#174]
Hey,

I'm trying to find out which knesset member voted for a certain bill, how can I do that? I can't find out how can I join this data? Can you please help me guys?

Thanks :)

**Comment by OriHoch** [comment]
hi, you can get votes details from this query (it's public, you just need to log-in with any google account):
https://app.redash.io/hasadna/queries/248417

alternatively, you can download the full data from here (also public after login with google account): 
https://console.cloud.google.com/storage/browser/knesset-data-pipelines/data/votes/view_vote_rslts_hdr_approved/?project=hasadna-oknesset

It contains all details for each vote, including IDs of Knesset members which voted on this vote (for / against / abstained)

to get the details of an MK from the ID you can use this data package:
https://console.cloud.google.com/storage/browser/knesset-data-pipelines/data/members/mk_individual/?project=hasadna-oknesset

Please contact me via email if you have more questions as I'm not responsive on the issues here: ori AT uumpa DOT com
