### ISSUE TITLE
What is the difference between this repo

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data-pipelines#2]
And knesset-data-datapackage and knesset-data-python (And knesset-data-django which I might understand . not sure)

**Comment by OriHoch** [comment]
Now that we have support for python 3.6 in knesset-data-python, this repo contains the implementation of the datapackage pipelines for knesset-data.

This is similar in some ways to knesset-data-datapackage but more standardized and uses the same architecture as open budget.

One of the advantages of this framework is the ability to dump data into various destionations, most relevant for us - is PostgreSql and Elasticsearch - also, same as open budget do.

The downside of this is that it breaks support for the existing Open Knesset website and also for knesset-data-django - we are not using django orm anymore in this repo and we don't intend to support compatibility to legacy tables

This relates to the changes we discussed in latest Open Knesset meetings - where we decided on gradually reducing support for open knesset website and instead focus on minimal apps that provide specific functionality.

**Comment by alonisser** [comment]
So everything migrated here would be killed from Oknesset?  Can we get a summary of the meeting about killing open-knesset. Should community members and past and current contributors who happen not to be available in a week before notice for a specific date be notified with a summary and road map? 

Although if the plan is not to use knesset-data-django I rather merge it for now back Open-knesset. I don't see any value in this separation in the current state. and the cross imports make it very hard to me to follow the code
