### ISSUE TITLE
Lack of data in 'members_presence' table

### ISSUE THREAD

**Issue by bobiboMC** [hasadna/knesset-data-pipelines#213]
I found that there is lack of data for some knesset members or ministers in 'members_presence' table.
For example:
איתמר בן גביר
משה אבוטבול
חיים ביטון
גלית דיסטל אטבריאן

**Comment by OriHoch** [comment]
fixed in https://github.com/hasadna/knesset-data-pipelines/commit/0a37a9cbdb4cbbb21a4fb98b0abe2dba4a1966ca
