### ISSUE TITLE
Duplicate and lack of data in 'members_mk_individual' table

### ISSUE THREAD

**Issue by bobiboMC** [hasadna/knesset-data-pipelines#217]
This table has duplicate columns , "FirstName" is same as "mk_individual_first_name", "LastName" is same as "mk_individual_name".
Also, No data for "mk_individual_first_name_eng" column and "mk_individual_first_name_eng" for each row.
Not sure what's "mk_status_id" column and if it's necessary because it's value is 0 for each row.
"mk_individual_photo" column is a placeholder link photo for each row, real photos need to be added for each row in the future.

**Comment by OriHoch** [comment]
regarding english names, I opened a new issue - #220

**Comment by OriHoch** [comment]
regarding mk photos - opened an issue - #221

**Comment by OriHoch** [comment]
other issues are probably due to old data or changes in schema, but we don't want to remove fields because some other pipelines or users might depend on them
