### ISSUE TITLE
should have a pipeline that generates static html files with friendly metadata and links to the available data

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data-pipelines#35]
### reproduction
* as a content or product designer - you want to review the available data to determine the best ways to use it / visualize it

#### expected
* should have a centralized place where you can see all the available data
* should have links to the related data and metadata, for example:
  * link to the relevant metabase dashboard / questions
  * links to related data files

#### actual
* you can see status and descriptions in the pipelines dashboard, but they are not clear
* there is a direct link to metabase dashboard ([for example - committees dashboard](http://next.oknesset.org/metabase/public/dashboard/57604bd2-73f3-4fbc-943f-53bf45287641)) - but you have to know about it
* there are html files with table schemas ([for example](https://next.oknesset.org/data/table_schemas/kns_committee.html)) - but also, you have to know about it

### implementation notes
* should add a daily pipeline that will generate static html files in data/ directory
* this pipeline should go over all the pipeline specs (and possibly status) - and aggregate related data to static html files

**Comment by abezgauzdina** [comment]
I am working on it

**Comment by OriHoch** [comment]
closing the issue as the initial work on aggregated html is merged and deployed

files are available for download publically, e.g. http://minio.oknesset.org/bills/index.html

opened follow-up issues:
* #69
* #70
