### ISSUE TITLE
docker should support running in manual mode - without celery workers and beat

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data-pipelines#7]
currently when the docker starts it runs celery tasks and scheduler

in development or when debugging problems this is not desired, sometimes you want to only start and then run pipelines manually (using the dpp cli)

the entrypoin should support a parameter that will cause the celery workers and beat to not start

**Comment by akariv** [comment]
The celery and server only start when running the docker image in the 'server' - see here https://github.com/frictionlessdata/datapackage-pipelines#quick-start

**Comment by OriHoch** [comment]
added option to set concurrency via environment variable, can be set to 0 to disable workers - 
28c5cae835fd9c4b0ea722a82ae28b6fb8429b5a
