### ISSUE TITLE
pipelines should produce datapackages of bills info

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data-pipelines#8]

**Comment by OriHoch** [comment]
I assume that by datapackages you mean a .zip file compatible with frictionlessdata datapcakage specs?
what's the use-case for this? e.g. why do you need datapackages of bills info?

if it's accessible via redash where you can download csv from redash - wouldn't that be better?

**Comment by alonisser** [comment]
Redash can't be automated, only a view, and not a good one in my opinon. I need the data either to feed back to Open Knesset or Perhaps consume in another project I'm thinking about

Also not sure how to download the committees part

**Comment by arikfr** [comment]
I'm not sure what you mean by automated, but anything you can do from the UI you can do with the API. 

It's very easy to consume the data via the API either as csv or JSON. Although above certain dataset size it makes less sense to use Redash as a proxy.

**Comment by OriHoch** [comment]
We can always add an API, but I would prefer to have it in a different repo. It could be installed as part of our docker swarm, so it will have access to the db and any other data

**Comment by arikfr** [comment]
I should've been more explicit that by UI and API I meant Redash's API and UI. From your comment it seemed to me that you already use Redash, so you already have an API.

**Comment by alonisser** [comment]
Thanks @arikfr I didn't know redash had an api. I'll take a look. Although I suspect it isn't meant to be used as an API server for another project.  @OriHoch I'm not sure downloading csvs is helpful, but I'll check

**Comment by OriHoch** [comment]
also, the current redash installation I did is very minimal and on my own private server..
once we move to a proper server, I could let someone else have access to it and set it up properly with all features

**Comment by OriHoch** [comment]
@alonisser - I'm sure @akariv will be happy to show you the full features of redash - as they use it in budget key

**Comment by OriHoch** [comment]
https://minio.oknesset.org/bills/datapackage.json
